CREATE TABLE IF NOT EXISTS users (
id SERIAL NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(255) NOT NULL,
active BOOLEAN NOT NULL,
role VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS income(
id SERIAL NOT NULL,
category VARCHAR(100) NOT NULL,
amount NUMERIC NOT NULL,
user_id SERIAL NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (user_id) references users(id)
);

CREATE TABLE IF NOT EXISTS expensive(
id SERIAL NOT NULL,
category VARCHAR(100) NOT NULL,
amount NUMERIC NOT NULL,
user_id SERIAL NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS verification_token(
id SERIAL NOT NULL,
expiry_date TIMESTAMP,
token VARCHAR(125) NOT NULL,
user_id SERIAL NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES users(id)
);
